### ISSUE TITLE
Error botocore

### ISSUE THREAD

**Issue by rpaullouis-fft** [aws-solutions/instance-scheduler-on-aws#326]
I am using the last version of the product (SO0030  v1.4.1) and trying to schedule postgresql RDS on a remote account.
I am experiencing a botocore error `Shape is missing requiered key` each time the application must operate on a RDS. It does not behave chaotically like I read on other posts. This message prompts each time the scheduler must act (start or stop) on a rds.

I don't have any problem with EC2 scheduling. It looks like the same error as other issues posted here, ([#256 ](https://github.com/aws-solutions/aws-instance-scheduler/issues/256) or [#240 ](https://github.com/aws-solutions/aws-instance-scheduler/issues/240)) 

But I couldn't find any working solution in those posts.

CloudFormation parameters:

DefaultTimezone: `Europe/Paris`
LogRetentionDays: `30`
MemorySize: `1024`
Regions: `eu-west-1`
ScheduleLambdaAccount: `Yes`
ScheduleRdsClusters: `Yes`
ScheduledServices: `Both`
SchedulerFrequency: `1`
SchedulingActive: `Yes`
SendAnonymousData: `Yes`
StartedTags: `-`
StoppedTags:` -`
TagName: `Schedule`
Trace: `Yes`
UseCloudWatchMetrics: `No`

Here are cloudwatch logs from the stack log group.
```
Logstream: InstanceScheduler-20220916

by handler SchedulerRequestHandler: (Shape is missing required key 'type': OrderedDict([('members', OrderedDict([('SourceRegion', OrderedDict([('shape', 'String'), ('documentation', '<p>The ID of the region that contains the source for the db instance.</p>')]))]))]))
Traceback (most recent call last):
  File "/var/runtime/botocore/model.py", line 622, in get_shape_by_name
    shape_cls = self.SHAPE_CLASSES.get(shape_model['type'], Shape)
KeyError: 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/main.py", line 71, in lambda_handler
    result = handler.handle_request()
  File "/var/task/requesthandlers/scheduler_request_handler.py", line 133, in handle_request
    lambda_account=self.lambda_account, context=self._context, logger=self._logger)
  File "/var/task/schedulers/instance_scheduler.py", line 220, in run
    response[account.name] = self._process_account(account)
  File "/var/task/schedulers/instance_scheduler.py", line 267, in _process_account
    for instance in self._scheduled_instances_in_region(account, region):
  File "/var/task/schedulers/instance_scheduler.py", line 184, in _scheduled_instances_in_region
    schedulers.PARAM_CONTEXT: self._context
  File "/var/task/schedulers/rds_service.py", line 277, in get_schedulable_instances
    instances = self.get_schedulable_rds_instances(kwargs)
  File "/var/task/schedulers/rds_service.py", line 253, in get_schedulable_rds_instances
    kwargs=kwargs)
  File "/var/task/schedulers/rds_service.py", line 199, in get_schedulable_resources
    rds_resp = fn(**describe_arguments)
  File "/var/task/boto_retry/__init__.py", line 78, in wrapped_api_method
    return retry_strategy.call(client_or_resource, name, args)
  File "/var/task/boto_retry/aws_service_retry.py", line 136, in call
    raise ex
  File "/var/task/boto_retry/aws_service_retry.py", line 118, in call
    resp = method(**call_arguments)
  File "/var/runtime/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 706, in _make_api_call
    operation_model, request_dict, request_context)
  File "/var/runtime/botocore/client.py", line 725, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/var/runtime/botocore/endpoint.py", line 104, in make_request
    return self._send_request(request_dict, operation_model)
  File "/var/runtime/botocore/endpoint.py", line 137, in _send_request
    request, operation_model, context)
  File "/var/runtime/botocore/endpoint.py", line 168, in _get_response
    request, operation_model)
  File "/var/runtime/botocore/endpoint.py", line 228, in _do_get_response
    operation_model, parser,
  File "/var/runtime/botocore/endpoint.py", line 241, in _add_modeled_error_fields
    error_shape = service_model.shape_for_error_code(error_code)
  File "/var/runtime/botocore/model.py", line 284, in shape_for_error_code
    return self._error_code_cache.get(error_code, None)
  File "/var/runtime/botocore/utils.py", line 931, in __get__
    computed_value = self._fget(obj)
  File "/var/runtime/botocore/model.py", line 289, in _error_code_cache
    for error_shape in self.error_shapes:
  File "/var/runtime/botocore/utils.py", line 931, in __get__
    computed_value = self._fget(obj)
  File "/var/runtime/botocore/model.py", line 305, in error_shapes
    error_shape = self.shape_for(shape_name)
  File "/var/runtime/botocore/model.py", line 281, in shape_for
    shape_name, member_traits)
  File "/var/runtime/botocore/model.py", line 625, in get_shape_by_name
    % shape_model)
botocore.model.InvalidShapeError: Shape is missing required key 'type': OrderedDict([('members', OrderedDict([('SourceRegion', OrderedDict([('shape', 'String'), ('documentation', '<p>The ID of the region that contains the source for the db instance.</p>')]))]))])```

**Comment by hearde** [comment]
It sounds like errors were being logged when the solution found an instance that could not be started/stopped (an instance that's a member of a multi-AZ cluster, Aurora serverless). This is expected, because the scheduler is unable to perform the requested action on the instance. Please reopen this issue if you are observing any other incorrect behavior.
